#!/bin/sh

export EDITOR=mtt-editor

if [ -f $HOME/.bash_profile ]; then
    alias refresh-profile='source $HOME/.bash_profile'
else
    alias refresh-profile='source $HOME/.profile'
fi

case ":${PATH}:" in
    *:"$HOME/.local/bin":*)
        ;;
    *)
        export PATH="$PATH:$HOME/.local/bin"
        ;;
esac
